name: flash_chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_speed_dial: ^1.2.5
  share: ^0.6.5+4
  double_back_to_close_app: ^1.2.0
  favorite_button: ^0.0.3
  font_awesome_flutter: ^8.11.0
  flutter_svg: ^0.19.1
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.12.9+5
  fluttertoast: ^7.1.6
  image_picker: ^0.6.4
  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.0.6
  cached_network_image: ^2.5.0
  intl: ^0.15.7
  firebase_messaging:

  flutter_local_notifications: 1.4.0
  photo_view: ^0.5.0
  giffy_dialog: ^1.8.0
  flutter_image_compress: ^0.7.0
  like_button: ^1.0.4
  bottom_navy_bar: ^5.6.0
  google_fonts: ^1.1.2
  cupertino_icons: ^0.1.3

  rubber: ^0.4.0
  infinite_listview: ^1.0.0
  modal_bottom_sheet: ^1.0.0+1
  cupertino_radio_choice: 1.0.0+1
  numberpicker: ^1.3.0
  shimmer: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path : "images/launcher/logo.png"


flutter:

  uses-material-design: true


  assets:
    - images/launcher/logo.png
    - images/launcher/logo1.png
    - images/img_not_available.jpeg
    - images/google.png
    - images/heart.svg
    - images/user.jpg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
